const state = { mode: 'client', view: 'home', balanceVisible: true };
const icons = { home: '⌂', wallet: '▣', pay: '⌗', activity: '↗', cards: '▤', benefits: '✦', profile: '♙', ops: '▦' };
const movements = [
  ['↑', 'Juan Pérez', 'Transferencia recibida', '+ B/. 150.00', 'positive'],
  ['🛒', 'Supermercado Rey', 'Compras · Hoy, 09:12', '- B/. 35.50', ''],
  ['▣', 'Metro de Panamá', 'Transporte · Ayer, 18:45', '- B/. 2.50', ''],
  ['◉', 'Amazon', 'Compra en línea · 16 sep', '- B/. 125.00', '']
];

const clientViews = {
  home: { title: 'Hola, Paul', subtitle: 'Aquí está el resumen de tus finanzas' },
  wallet: { title: 'Mi Wallet', subtitle: 'Tus cuentas, saldos y productos' },
  pay: { title: 'Pagar', subtitle: 'Paga con tu Wallet o tarjeta' },
  activity: { title: 'Actividad', subtitle: 'Historial detallado de tus operaciones' },
  cards: { title: 'Mis tarjetas', subtitle: 'Administra tus medios de pago' },
  benefits: { title: 'Beneficios', subtitle: 'Recompensas para ti' },
  profile: { title: 'Mi perfil', subtitle: 'Identidad, seguridad y permisos' }
};

const opsViews = {
  overview: { title: 'Centro de operaciones', subtitle: 'Control operativo de PanamáWallet' },
  customers: { title: 'Clientes', subtitle: 'Identidad, KYC/KYB y estados de cuenta' },
  risk: { title: 'Riesgo y cumplimiento', subtitle: 'Alertas, casos y controles de operación' },
  reconciliation: { title: 'Conciliación', subtitle: 'Cuadre de ledger, bancos y procesadores' },
  partners: { title: 'Aliados y capacidades', subtitle: 'Catálogo curado y ciclo de vida' },
  analytics: { title: 'Analítica', subtitle: 'Indicadores del ecosistema financiero' },
  settings: { title: 'Configuración', subtitle: 'Productos, reglas, límites y comisiones' }
};

function clientNav() { return [['home','Inicio'],['wallet','Wallet'],['pay','Pagar'],['activity','Actividad'],['profile','Perfil']]; }
function opsNav() { return [['overview','Resumen'],['customers','Clientes'],['risk','Riesgo'],['reconciliation','Conciliación'],['partners','Aliados'],['analytics','Analítica'],['settings','Configuración']]; }
function metric(label, value, detail, tone = '') { return `<article class="metric-card ${tone}"><span>${label}</span><strong>${value}</strong><small>${detail}</small></article>`; }
function movementRows(limit = movements.length) { return movements.slice(0, limit).map(([icon, name, detail, amount, tone]) => `<article class="movement-row"><span class="movement-symbol ${tone}">${icon}</span><div><b>${name}</b><small>${detail}</small></div><strong class="${tone}">${amount}</strong></article>`).join(''); }

function renderShell() {
  const nav = state.mode === 'client' ? clientNav() : opsNav();
  const views = state.mode === 'client' ? clientViews : opsViews;
  const current = views[state.view] || views[Object.keys(views)[0]];
  document.body.innerHTML = `<main class="prototype-shell ${state.mode === 'ops' ? 'ops-shell' : ''}">
    <aside class="app-sidebar"><div class="brand"><span>◈</span><b>Panamá<span>Wallet</span></b></div><div class="workspace-switch"><span class="workspace-dot">${state.mode === 'client' ? 'PP' : 'OP'}</span><div><b>${state.mode === 'client' ? 'Paul Pérez' : 'Operaciones'}</b><small>${state.mode === 'client' ? 'Cuenta personal' : 'Vista interna'}</small></div><span>⌄</span></div><nav class="side-nav">${nav.map(([id,label]) => `<button class="side-item ${state.view === id ? 'active' : ''}" data-view="${id}"><span>${icons[id] || '◈'}</span>${label}</button>`).join('')}</nav><button class="mode-switch" data-mode-switch>${state.mode === 'client' ? '▦  Abrir backoffice' : '←  Volver a cliente'}</button><div class="sidebar-footer"><span class="secure-dot"></span><span>Operación protegida<br><small>Panamá · v1.12</small></span></div></aside>
    <section class="app-main"><header class="main-header"><div class="device-status"><span>9:41</span><span>●●●  ⌁  ▰</span></div><div class="header-row"><button class="menu-button" data-toast="Menú de la aplicación">☰</button><div class="header-copy"><p class="eyebrow">${state.mode === 'client' ? 'MARTES, 18 DE SEPTIEMBRE' : 'OPERACIÓN · TIEMPO REAL'}</p><h1>${current.title}</h1><p>${current.subtitle}</p></div><div class="header-actions"><button class="header-icon" data-toast="Centro de notificaciones">♧<i></i></button><button class="profile-chip">${state.mode === 'client' ? 'PP' : 'OP'}</button></div></div></header><div class="view-content">${state.mode === 'client' ? renderClientView() : renderOpsView()}</div><nav class="mobile-nav">${nav.slice(0,5).map(([id,label]) => `<button class="mobile-item ${state.view === id ? 'active' : ''}" data-view="${id}"><span>${icons[id] || '◈'}</span>${label}</button>`).join('')}</nav></section>
  </main><div class="toast" role="status"></div>${renderSheet()}`;
  const payOptions = document.querySelector('.pay-options');
  if (payOptions && !payOptions.querySelector('[data-yappy]')) payOptions.insertAdjacentHTML('beforeend', '<button data-yappy data-toast="Yappy abierto"><span>Y</span><b>Yappy</b><small>Paga y envía dinero con Yappy</small></button>');
  document.querySelectorAll('.payment-card').forEach((card) => {
    const flip = document.createElement('div');
    flip.className = 'card-flip';
    card.parentNode.insertBefore(flip, card);
    flip.appendChild(card);
    flip.insertAdjacentHTML('beforeend', '<div class="payment-card card-back"><div class="magnetic-strip"></div><span class="back-number">4582  ••••  ••••  9017</span><div class="back-details"><span>VALID THRU<br><b>09/29</b></span><span>CVV<br><b>•••</b></span><span class="back-brand">VISA</span></div><small class="back-note">Tarjeta protegida por PanamáWallet</small></div>');
    flip.addEventListener('click', () => flip.classList.toggle('flipped'));
  });
  bindEvents();
}

function renderClientView() {
  if (state.view === 'wallet') return `<div class="page-grid"><section class="wide-panel balance-panel"><div class="panel-header"><div><span class="eyebrow dark">SALDO CONSOLIDADO</span><h2>Tu dinero, en un solo lugar</h2></div><button class="outline-button">Estados de cuenta</button></div><div class="big-balance"><span>Saldo disponible</span><strong>${state.balanceVisible ? 'B/. 2,450.75' : 'B/. ••••••'}</strong><button data-balance>◉</button></div><div class="wallet-list"><div class="list-head"><b>Cuentas y Wallets</b><button class="text-button">+ Agregar</button></div>${[['Cuenta Corriente','B/. 1,250.00','•••• 1234'],['Cuenta de Ahorros','B/. 820.45','•••• 5678'],['Wallet Panamá','B/. 60.30','•••• 9090'],['Wallet Dólares','USD 45.20','•••• 6620']].map(([name,amount,number]) => `<div class="wallet-row"><span class="wallet-icon">▣</span><div><b>${name}</b><small>${number}</small></div><strong>${amount}</strong><span>›</span></div>`).join('')}</div></section><aside class="side-column">${metric('Disponible','B/. 2,450.75','3 cuentas · 2 wallets')}${metric('Retenido','B/. 84.00','2 operaciones pendientes','amber')}${metric('Este mes','B/. 1,284.20','+12.8% vs. anterior','green')}</aside></div>`;
  if (state.view === 'pay') return `<section class="page-intro"><div class="qr-preview"><div class="qr-code">▦<br>▦</div></div><div><span class="eyebrow dark">PUNTO DE ENTRADA UNIVERSAL</span><h2>Paga en cualquier lugar</h2><p>Escanea un QR, usa un enlace de pago o selecciona una capacidad del ecosistema.</p><div class="pay-options"><button data-toast="Cámara QR activada"><span>⌗</span><b>Escanear QR</b><small>Comercio, persona o servicio</small></button><button data-toast="Enlace de pago generado"><span>↗</span><b>Crear enlace</b><small>Solicita o recibe un pago</small></button><button data-toast="Servicios abiertos"><span>⌘</span><b>Pagar servicios</b><small>Telecomunicaciones y hogar</small></button><button data-toast="Pase U abierto"><span>◉</span><b>Pase U</b><small>Recarga y consulta tu beneficio</small></button></div></div></section>`;
  if (state.view === 'activity') return `<section class="wide-panel activity-panel"><div class="filter-bar"><div class="segmented"><button class="selected">Todos</button><button>Recibidos</button><button>Enviados</button><button>Pagos</button></div><button class="outline-button">Filtrar ˅</button></div><div class="activity-total"><div><span>Movimientos de septiembre</span><strong>B/. 1,842.70</strong></div><span class="positive">+ 8.4%</span></div>${movementRows()}</section>`;
  if (state.view === 'cards') return `<div class="page-grid"><section class="wide-panel"><div class="panel-header"><div><span class="eyebrow dark">MEDIOS DE PAGO</span><h2>Tarjetas activas</h2></div><button class="primary-small" data-toast="Solicitud de tarjeta iniciada">+ Solicitar tarjeta</button></div><div class="card-gallery"><article class="payment-card large-card"><div class="card-top">▦ &nbsp;⌁ <span>◈</span></div><div class="card-name">Visa Platinum</div><div class="card-bottom">•••• 4582 <b>VISA</b></div></article><article class="payment-card virtual-card"><div class="card-top">VIRTUAL <span>◈</span></div><div class="card-name">Wallet Virtual</div><div class="card-bottom">•••• 9017 <b>VISA</b></div></article></div><div class="settings-list"><div><span>◉</span><b>Compras en línea</b><label class="toggle on"><i></i></label></div><div><span>⌁</span><b>Compras internacionales</b><label class="toggle on"><i></i></label></div><div><span>▣</span><b>Retiros en ATM</b><label class="toggle"><i></i></label></div></div></section><aside class="side-column">${metric('Límite diario','B/. 5,000','Disponible hoy')}${metric('Estado','Activa','Visa Platinum','green')}</aside></div>`;
  if (state.view === 'benefits') return `<div class="page-grid"><section class="wide-panel"><div class="panel-header"><div><span class="eyebrow dark">LEALTAD Y RECOMPENSAS</span><h2>Tus beneficios</h2></div><button class="outline-button">Ver historial</button></div><div class="rewards-hero"><span>Saldo de puntos</span><strong>2,840 pts</strong><small>Canjea tus puntos por beneficios exclusivos</small><button class="primary-small">Explorar recompensas</button></div><div class="benefit-grid"><article><span>↗</span><b>10% cashback</b><small>En restaurantes aliados</small></article><article><span>✦</span><b>Metro de Panamá</b><small>B/. 0.50 de descuento</small></article><article><span>♢</span><b>Referidos</b><small>Gana B/. 5 por amigo</small></article></div></section><aside class="side-column">${metric('Cashback acumulado','B/. 18.40','Este mes','green')}${metric('Nivel actual','Platinum','2,160 pts para subir','amber')}</aside></div>`;
  if (state.view === 'profile') return `<div class="page-grid"><section class="wide-panel"><div class="profile-hero"><div class="profile-avatar">PP</div><div><span class="eyebrow dark">IDENTIDAD VERIFICADA</span><h2>Paul Pérez</h2><p>paul.perez@email.com · +507 6123-4567</p></div><span class="verified">✓ Verificado</span></div><div class="settings-list profile-list"><div data-toast="Datos personales abiertos"><span>♙</span><b>Datos personales</b><small>Información de tu perfil</small><strong>›</strong></div><div data-toast="Seguridad abierta"><span>⌾</span><b>Seguridad y dispositivos</b><small>Biometría, passkey y sesiones activas</small><strong>›</strong></div><div data-toast="Consentimientos abiertos"><span>◈</span><b>Consentimientos y aliados</b><small>3 capacidades con acceso autorizado</small><strong>›</strong></div><div data-toast="Preferencias abiertas"><span>♧</span><b>Notificaciones</b><small>Push, correo y SMS</small><strong>›</strong></div></div></section><aside class="side-column">${metric('Nivel KYC','Completo','Próxima revisión: sep 2027','green')}${metric('Dispositivos','2 activos','Último acceso hace 4 min')}</aside></div>`;
  return `<div class="dashboard-grid"><section class="hero-balance"><div class="hero-copy"><span class="eyebrow">SALDO DISPONIBLE</span><button data-balance class="hero-eye">${state.balanceVisible ? '◉' : '◌'}</button><strong>${state.balanceVisible ? 'B/. 2,450.75' : 'B/. ••••••'}</strong><small>En total: 3 cuentas · 2 wallets · 4 tarjetas</small></div><span class="hero-arrow">›</span></section><section class="quick-grid">${[['send','➤','Enviar dinero'],['receive','⇩','Recibir dinero'],['pay','⌗','Pagar'],['bank','⌂','Transferir a banco'],['more','•••','Más']].map(([action,icon,label]) => `<button data-action="${action}"><span>${icon}</span><b>${label}</b></button>`).join('')}</section><section class="wide-panel"><div class="panel-header"><div><span class="eyebrow dark">ACTIVIDAD RECIENTE</span><h2>Últimos movimientos</h2></div><button class="text-button" data-view="activity">Ver todos ›</button></div>${movementRows(3)}</section><aside class="side-column"><div class="mini-card"><div class="panel-header"><h3>Mi tarjeta principal</h3><button class="text-button" data-view="cards">Ver ›</button></div><article class="payment-card"><div class="card-top">▦ &nbsp;⌁ <span>◈</span></div><div class="card-name">Visa Platinum</div><div class="card-bottom">•••• 4582 <b>VISA</b></div></article></div>${metric('Retenido','B/. 84.00','2 pagos pendientes','amber')}</aside></div>`;
}

function renderOpsView() {
  if (state.view === 'customers') return `<section class="ops-layout"><div class="wide-panel"><div class="panel-header"><div><span class="eyebrow dark">GESTIÓN DE CLIENTES</span><h2>Clientes y KYC</h2></div><button class="primary-small" data-toast="Alta de cliente abierta">+ Nuevo cliente</button></div><div class="table-tools"><input placeholder="Buscar por nombre, ID o correo"><button class="outline-button">Filtros ˅</button></div><div class="data-table"><div class="table-row table-head"><span>Cliente</span><span>Estado de identidad</span><span>Wallet</span><span>Última actividad</span><span></span></div>${[['Paul Pérez','Verificado','B/. 2,450.75','Hace 4 min','green'],['María González','Pendiente KYC','B/. 820.20','Hace 1 h','amber'],['Comercial Istmo, S.A.','KYB en revisión','B/. 12,480.00','Ayer','amber'],['Juan Rodríguez','Verificado','B/. 420.50','18 sep','green']].map(([name,status,balance,time,tone]) => `<div class="table-row"><span><b>${name}</b><small>Cliente · Panamá</small></span><span class="status ${tone}">${status}</span><span>${balance}</span><span>${time}</span><button class="row-more">•••</button></div>`).join('')}</div></div><aside class="side-column">${metric('Clientes activos','24,892','+4.8% este mes','green')}${metric('KYC pendientes','184','12 de alta prioridad','amber')}${metric('Casos AML','23','4 nuevos hoy','red')}</aside></section>`;
  if (state.view === 'risk') return `<section class="ops-layout"><div class="wide-panel"><div class="panel-header"><div><span class="eyebrow dark">CONTROL TRANSACCIONAL</span><h2>Casos que requieren atención</h2></div><div class="segmented"><button class="selected">Activos 12</button><button>Resueltos</button></div></div>${[['Alerta de velocidad','Transferencia fuera de patrón · Paul Pérez','Alto','Hace 4 min','red'],['KYC pendiente','Documento no coincide con datos de cliente','Medio','Hace 28 min','amber'],['Comercio bajo monitoreo','Aumento de contracargos · Supermercado Rey','Medio','Hace 1 h','amber'],['Lista PEP','Coincidencia requiere revisión manual','Alto','Hace 2 h','red']].map(([title,desc,level,time,tone]) => `<article class="case-row"><span class="case-icon ${tone}">!</span><div><b>${title}</b><p>${desc}</p><small>${time}</small></div><span class="status ${tone}">${level}</span><button class="outline-button">Revisar</button></article>`).join('')}</div><aside class="side-column">${metric('Risk score medio','18.4','Dentro de rango','green')}${metric('Operaciones retenidas','7','B/. 1,240.00','amber')}${metric('Alertas hoy','34','-8.2% vs. ayer','green')}</aside></section>`;
  if (state.view === 'reconciliation') return `<section class="ops-layout"><div class="wide-panel"><div class="panel-header"><div><span class="eyebrow dark">LEDGER Y SETTLEMENT</span><h2>Conciliación diaria</h2></div><button class="primary-small" data-toast="Nueva conciliación iniciada">+ Ejecutar conciliación</button></div><div class="recon-status"><div class="recon-ring">98.7%<small>cuadrado</small></div><div><b>Cierre del 18 sep 2026</b><p>Última ejecución hace 14 min · 8,432 operaciones procesadas</p><span class="status green">Sin diferencias críticas</span></div></div><div class="data-table"><div class="table-row table-head"><span>Fuente</span><span>Operaciones</span><span>Cuadrado</span><span>Diferencias</span><span>Estado</span></div>${[['Banco custodio','4,280','B/. 842,190.20','2','Completado'],['Procesador tarjetas','3,410','B/. 128,450.00','8','Revisar'],['Adquirencia QR','742','B/. 24,890.40','0','Completado']].map(([source,ops,amount,diffs,status]) => `<div class="table-row"><span><b>${source}</b><small>Archivo + API</small></span><span>${ops}</span><span>${amount}</span><span>${diffs}</span><span class="status ${status === 'Completado' ? 'green' : 'amber'}">${status}</span></div>`).join('')}</div></div><aside class="side-column">${metric('Fondos de clientes','B/. 4.82 M','Respaldados','green')}${metric('En tránsito','B/. 18,420','12 operaciones')}${metric('Diferencias','10','2 requieren acción','amber')}</aside></section>`;
  if (state.view === 'partners') return `<section class="ops-layout"><div class="wide-panel"><div class="panel-header"><div><span class="eyebrow dark">ECOSISTEMA CURADO</span><h2>Aliados y capacidades</h2></div><button class="primary-small" data-toast="Admisión de aliado iniciada">+ Proponer aliado</button></div><div class="partner-grid">${[['Supermercado Rey','Pagos QR · Cashback','Activa','green','96.4%'],['Metro de Panamá','Movilidad · Recargas','Activa','green','99.1%'],['FinanciaYa','Crédito personal','En certificación','amber','—'],['Salud Plus','Marketplace · Salud','Suspendida','red','—']].map(([name,cap,status,tone,uptime]) => `<article class="partner-card"><div class="partner-logo">${name.slice(0,2)}</div><div><b>${name}</b><small>${cap}</small></div><span class="status ${tone}">${status}</span><hr><div><small>Disponibilidad</small><strong>${uptime}</strong></div><button class="text-button">Gestionar ›</button></article>`).join('')}</div></div><aside class="side-column">${metric('Aliados activos','18','2 en certificación','green')}${metric('Capacidades publicadas','42','En 7 verticales')}${metric('Reputación media','4.8 / 5','Basada en operaciones','green')}</aside></section>`;
  if (state.view === 'analytics') return `<section class="analytics-grid"><div class="wide-panel chart-panel"><div class="panel-header"><div><span class="eyebrow dark">INTELIGENCIA FINANCIERA</span><h2>Volumen transaccional</h2></div><button class="outline-button">Últimos 30 días ˅</button></div><div class="chart"><div class="chart-y"><span>B/. 200k</span><span>B/. 100k</span><span>B/. 0</span></div><svg viewBox="0 0 700 220" preserveAspectRatio="none" aria-label="Gráfico de volumen"><path d="M0 190 C60 170 65 135 120 155 S180 124 235 140 S285 80 340 108 S400 94 450 120 S510 45 560 82 S620 68 700 22 L700 220 L0 220Z" fill="rgba(8,104,217,.12)"/><path d="M0 190 C60 170 65 135 120 155 S180 124 235 140 S285 80 340 108 S400 94 450 120 S510 45 560 82 S620 68 700 22" fill="none" stroke="#0868d9" stroke-width="4"/></svg><div class="chart-x"><span>20 ago</span><span>27 ago</span><span>3 sep</span><span>10 sep</span><span>18 sep</span></div></div></div>${metric('Usuarios activos','18,420','+12.6% mes a mes','green')}${metric('Volumen total','B/. 4.82 M','+8.4% mes a mes','green')}${metric('Ingresos por comisiones','B/. 82,410','+14.2% mes a mes','green')}${metric('Uso de tarjetas','68.4%','De clientes activos')}</section>`;
  if (state.view === 'settings') return `<section class="ops-layout"><div class="wide-panel"><div class="panel-header"><div><span class="eyebrow dark">CONTROL DE PRODUCTO</span><h2>Reglas y parámetros</h2></div><button class="primary-small" data-toast="Nueva versión de configuración">+ Nuevo parámetro</button></div><div class="settings-list config-list">${[['RB-001','Límite diario de transferencia','Pendiente de definición','amber'],['RB-011','Límites por producto y canal','Pendiente de definición','amber'],['RB-012','Ledger inmutable','Definida · v1.1','green'],['RB-020','Datos de tarjeta enmascarados','Definida · v1.1','green'],['RB-048','Parámetros versionados','Definida · v1.1','green']].map(([id,name,status,tone]) => `<div><span class="rule-id">${id}</span><b>${name}</b><small class="status ${tone}">${status}</small><strong>›</strong></div>`).join('')}</div></div><aside class="side-column">${metric('Reglas definidas','42','18 pendientes','amber')}${metric('Versión activa','1.1','Último cambio 18 sep')}${metric('Auditoría','100%','Acciones registradas','green')}</aside></section>`;
  return `<div class="ops-dashboard"><div class="ops-metrics">${metric('Usuarios activos','18,420','+12.6% mes a mes','green')}${metric('Volumen del día','B/. 284,190','1,842 operaciones','green')}${metric('Casos abiertos','23','4 de alta prioridad','amber')}${metric('Disponibilidad','99.98%','Todos los servicios','green')}</div><div class="ops-columns"><section class="wide-panel"><div class="panel-header"><div><span class="eyebrow dark">MONITOREO EN TIEMPO REAL</span><h2>Salud del ecosistema</h2></div><span class="live"><i></i> Actualizado ahora</span></div><div class="health-list">${[['Core Wallet y Ledger','Operativo','99.99%','green'],['Pagos y transferencias','Operativo','99.98%','green'],['KYC / AML','Operativo','99.95%','green'],['Procesador de tarjetas','Degradación controlada','98.70%','amber'],['Adquirencia QR','Operativo','99.91%','green']].map(([name,status,uptime,tone]) => `<div><span class="health-dot ${tone}"></span><b>${name}</b><span class="status ${tone}">${status}</span><small>${uptime}</small></div>`).join('')}</div></section><section class="wide-panel"><div class="panel-header"><div><span class="eyebrow dark">AUDITORÍA</span><h2>Actividad reciente</h2></div><button class="text-button" data-view="risk">Ver bitácora ›</button></div><div class="audit-list"><div><span>◉</span><b>Conciliación diaria completada<small>Operador: Ana Torres · hace 14 min</small></b></div><div><span>⌾</span><b>Regla RB-020 actualizada<small>Administrador · hace 26 min</small></b></div><div><span>!</span><b>Caso de riesgo asignado<small>Analista: Luis Moreno · hace 41 min</small></b></div></div></section></div></div>`;
}

function renderSheet() { return `<div class="sheet-backdrop" hidden><section class="action-sheet"><button class="close-sheet">×</button><div class="sheet-icon">➤</div><span class="eyebrow dark">OPERACIÓN FINANCIERA</span><h2>Enviar dinero</h2><p>Elige cómo quieres enviar fondos desde tu Wallet.</p><button class="sheet-option" data-toast="Contacto seleccionado">♙ <b>A un contacto</b><small>Desde tu lista de contactos</small><strong>›</strong></button><button class="sheet-option" data-toast="Cuenta bancaria seleccionada">▣ <b>A una cuenta bancaria</b><small>Transfiere a cualquier banco</small><strong>›</strong></button><button class="primary-button close-action">Continuar</button></section></div>`; }

function showToast(message) { const toast = document.querySelector('.toast'); toast.textContent = message; toast.classList.add('show'); clearTimeout(showToast.timeout); showToast.timeout = setTimeout(() => toast.classList.remove('show'), 2200); }
function bindEvents() {
  document.querySelectorAll('[data-view]').forEach((el) => el.addEventListener('click', () => { state.view = el.dataset.view; renderShell(); }));
  document.querySelector('[data-mode-switch]').addEventListener('click', () => { state.mode = state.mode === 'client' ? 'ops' : 'client'; state.view = state.mode === 'client' ? 'home' : 'overview'; renderShell(); });
  document.querySelectorAll('[data-toast]').forEach((el) => el.addEventListener('click', () => showToast(el.dataset.toast)));
  document.querySelectorAll('[data-action]').forEach((el) => el.addEventListener('click', () => { if (el.dataset.action === 'send') document.querySelector('.sheet-backdrop').hidden = false; else if (el.dataset.action === 'pay') { state.view = 'pay'; renderShell(); } else showToast(({ receive:'Recibir dinero', bank:'Transferencia bancaria', more:'Más servicios' })[el.dataset.action] + ' seleccionado'); }));
  document.querySelectorAll('[data-balance]').forEach((el) => el.addEventListener('click', () => { state.balanceVisible = !state.balanceVisible; renderShell(); }));
  const backdrop = document.querySelector('.sheet-backdrop');
  document.querySelector('.close-sheet').addEventListener('click', () => { backdrop.hidden = true; });
  document.querySelector('.close-action').addEventListener('click', () => { backdrop.hidden = true; showToast('Flujo de envío iniciado'); });
  backdrop.addEventListener('click', (event) => { if (event.target === backdrop) backdrop.hidden = true; });
}

renderShell();